image: gzero/platform-ci-runner:v2

stages:
  - test
  - build
  - deploy

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - vendor/
    - node_modules/

unit & functional tests:
  stage: test
  services:
    - name: postgres:9.6-alpine
      alias: db_tests_server
    - name: redis:3-alpine
      alias: redis
  variables:
    POSTGRES_PASSWORD: ""
    POSTGRES_USER: "gzero_cms"
    POSTGRES_DB: "gzero_cms"
    REDIS_PORT: "6379" # Bug caused by env variable collision docker/laravel
  artifacts:
    when: on_failure
    paths:
    - tests/_output
    - /tmp/laravel.log

  script:
    - phpdismod xdebug # disabling xdebug to speed up composer
    - composer install --prefer-dist --no-interaction --no-suggest --no-progress
    - "php vendor/bin/codecept run -n -c codeception.yml -o \"settings: lint: false\" -s acceptance --env platform,ml_disabled"
    - npm -s install # TODO Move frontend tests in to separate job
    - npm -s run lint
    - npm -s test -- --verbose

acceptance tests:
  stage: test
  services:
    - name: postgres:9.6-alpine
      alias: db
    - name: redis:3-alpine
      alias: redis
  variables:
    DEFAULT_HOST: "dev.gzero.pl"
    POSTGRES_PASSWORD: ""
    POSTGRES_USER: "gzero_cms"
    POSTGRES_DB: "gzero_cms"
    REDIS_PORT: "6379" # Bug caused by env variable collision docker/laravel
  artifacts:
    when: on_failure
    paths:
    - tests/_output
    - /tmp/laravel.log
  before_script:
    - rm -rf /var/www
    - ln -s "$(pwd)" /var/www
    - echo "127.0.0.1 dev.gzero.pl" >> /etc/hosts
    - echo "127.0.0.1 api.dev.gzero.pl" >> /etc/hosts
    - tests/chromedriver --url-base=/wd/hub --whitelisted-ips="" &
    - /start.sh &

  script:
    - phpdismod xdebug # disabling xdebug to speed up composer
    - composer install --prefer-dist --no-interaction --no-suggest --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:fresh
    - "CI_ACCEPTANCE_RUN=true php vendor/bin/codecept run -n -c codeception.yml -o \"settings: lint: false\" acceptance"

build:
  stage: build
  script:
    - composer install --prefer-dist --no-interaction --no-dev --no-suggest --no-progress --optimize-autoloader
    - npm -s install
    - npm -s run production
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - if [ -n "${CI_COMMIT_TAG}" ]; then docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .; fi
    - if [ -n "${CI_COMMIT_TAG}" ]; then docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}; fi
    - if [ -z "${CI_COMMIT_TAG}" ]; then docker build --pull -t ${CI_REGISTRY_IMAGE}:latest .; fi
    - if [ -z "${CI_COMMIT_TAG}" ]; then docker push ${CI_REGISTRY_IMAGE}:latest; fi
  only:
    - tags
    - master

deploy to staging:
  image: williamyeh/ansible:alpine3
  stage: deploy
  environment: staging
  before_script:
      - eval $(ssh-agent -s)
      - echo "$STAGING_SSH_PRIVATE_KEY" > ssh.key
      - chmod 600 ssh.key
      - ssh-add ssh.key
      - mkdir -p ~/.ssh
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - "ansible-playbook -i ansible/staging
      -e APP_KEY=$STAGING_APP_KEY
      -e APP_VERSION=$CI_COMMIT_TAG
      -e DOCKER_APP_IMAGE=$CI_REGISTRY_IMAGE
      -e DOMAIN=$STAGING_DOMAIN
      -e POSTGRES_USER=$STAGING_DB_USER
      -e POSTGRES_PASSWORD=$STAGING_DB_PASSWORD
      -e POSTGRES_DATABASE=$STAGING_DB_DATABASE
      -e MAIL_USERNAME=$STAGING_MAIL_USERNAME
      -e MAIL_PASSWORD=$STAGING_MAIL_PASSWORD
      -e UPLOAD_DISK=$STAGING_UPLOAD_DISK
      -e S3_KEY=$STAGING_S3_KEY
      -e S3_SECRET=$STAGING_S3_SECRET
      -e S3_BUCKET=$STAGING_S3_BUCKET
      -e LETSENCRYPT_EMAIL=$STAGING_LETSENCRYPT_EMAIL
      ansible/deploy-staging.yml"
  only:
    - tags
    - master

deploy to production:
  image: williamyeh/ansible:alpine3
  stage: deploy
  environment: production
  before_script:
    - eval $(ssh-agent -s)
    - echo "$PRODUCTION_SSH_PRIVATE_KEY" > ssh.key
    - chmod 600 ssh.key
    - ssh-add ssh.key
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - "ansible-playbook -i ansible/production
      -e APP_KEY=$PRODUCTION_APP_KEY
      -e APP_VERSION=$CI_COMMIT_TAG
      -e DOCKER_APP_IMAGE=$CI_REGISTRY_IMAGE
      -e DOMAIN=$PRODUCTION_DOMAIN
      -e POSTGRES_USER=$PRODUCTION_DB_USER
      -e POSTGRES_PASSWORD=$PRODUCTION_DB_PASSWORD
      -e POSTGRES_DATABASE=$PRODUCTION_DB_DATABASE
      -e MAIL_HOST=$PRODUCTION_MAIL_HOST
      -e MAIL_PORT=$PRODUCTION_MAIL_PORT
      -e MAIL_USERNAME=$PRODUCTION_MAIL_USERNAME
      -e MAIL_PASSWORD=$PRODUCTION_MAIL_PASSWORD
      -e MAIL_FROM_NAME=$PRODUCTION_MAIL_FROM_NAME
      -e MAIL_FROM_ADDRESS=$PRODUCTION_MAIL_FROM_ADDRESS
      -e UPLOAD_DISK=$PRODUCTION_UPLOAD_DISK
      -e S3_KEY=$PRODUCTION_S3_KEY
      -e S3_SECRET=$PRODUCTION_S3_SECRET
      -e S3_BUCKET=$PRODUCTION_S3_BUCKET
      -e LETSENCRYPT_EMAIL=$PRODUCTION_LETSENCRYPT_EMAIL
      ansible/deploy-production.yml"
  only:
    - tags
    - master
  when: manual