image: gzero/platform-ci-runner:v2

stages:
  - test
  - build
  - deploy

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - vendor/
    - node_modules/

unit & functional tests:
  stage: test
  services:
    - name: postgres:9.6-alpine
      alias: db_tests
    - name: redis:3-alpine
      alias: redis
  variables:
    POSTGRES_PASSWORD: ""
    POSTGRES_USER: "gzero_cms"
    POSTGRES_DB: "gzero_cms"
    REDIS_PORT: "6379" # Bug caused by env variable collision docker service & laravel
  artifacts:
    when: on_failure
    paths:
    - tests/_output
    - /tmp/laravel.log

  script:
    - phpdismod xdebug # disabling xdebug to speed up composer
    - composer install --prefer-dist --no-interaction --no-suggest --no-progress
    - "php vendor/bin/codecept run -n -c codeception.yml -o \"settings: lint: false\" -s acceptance --env platform,ml_disabled"
    - npm -s install # TODO Move frontend tests in to separate job
    - npm -s run lint
    - npm -s test -- --verbose

acceptance tests:
  stage: test
  services:
    - name: postgres:9.6-alpine
      alias: db
    - name: redis:3-alpine
      alias: redis
  variables:
    DEFAULT_HOST: "dev.gzero.pl"
    POSTGRES_PASSWORD: ""
    POSTGRES_USER: "gzero_cms"
    POSTGRES_DB: "gzero_cms"
    DB_PORT: "5432" # Bug caused by env variable collision docker service & laravel
    REDIS_PORT: "6379" # Bug caused by env variable collision docker service & laravel
  artifacts:
    when: on_failure
    paths:
    - tests/_output
    - /tmp/laravel.log
  before_script:
    - rm -rf /var/www
    - ln -s "$(pwd)" /var/www
    - echo "127.0.0.1 dev.gzero.pl" >> /etc/hosts
    - echo "127.0.0.1 api.dev.gzero.pl" >> /etc/hosts
    - tests/chromedriver --url-base=/wd/hub --whitelisted-ips="" &
    - /start.sh &

  script:
    - phpdismod xdebug # disabling xdebug to speed up composer
    - composer install --prefer-dist --no-interaction --no-suggest --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:fresh
    - "CI_ACCEPTANCE_RUN=true php vendor/bin/codecept run -n -c codeception.yml -o \"settings: lint: false\" acceptance"

build:
  stage: build
  script:
    - composer install --prefer-dist --no-interaction --no-dev --no-suggest --no-progress --optimize-autoloader
    - npm -s install
    - npm -s run production
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    # TAG
    - if [ -n "${CI_COMMIT_TAG}" ]; then docker build --pull --no-cache -t ${CI_REGISTRY_IMAGE}/web:${CI_COMMIT_TAG} -f Dockerfile.web .; fi
    - if [ -n "${CI_COMMIT_TAG}" ]; then docker build --pull --no-cache -t ${CI_REGISTRY_IMAGE}/worker:${CI_COMMIT_TAG} -f Dockerfile.worker .; fi
    - if [ -n "${CI_COMMIT_TAG}" ]; then docker push ${CI_REGISTRY_IMAGE}/web:${CI_COMMIT_TAG}; fi
    - if [ -n "${CI_COMMIT_TAG}" ]; then docker push ${CI_REGISTRY_IMAGE}/worker:${CI_COMMIT_TAG}; fi
    # LATEST
    - if [ -z "${CI_COMMIT_TAG}" ]; then docker build --pull --no-cache -t ${CI_REGISTRY_IMAGE}/web:latest -f Dockerfile.web .; fi
    - if [ -z "${CI_COMMIT_TAG}" ]; then docker build --pull --no-cache -t ${CI_REGISTRY_IMAGE}/worker:latest -f Dockerfile.worker .; fi
    - if [ -z "${CI_COMMIT_TAG}" ]; then docker push ${CI_REGISTRY_IMAGE}/web:latest; fi
    - if [ -z "${CI_COMMIT_TAG}" ]; then docker push ${CI_REGISTRY_IMAGE}/worker:latest; fi
  only:
    - tags
    - master

deploy to staging:
  image: williamyeh/ansible:alpine3
  stage: deploy
  environment: staging
  before_script:
      - eval $(ssh-agent -s)
      - echo "$STAGING_SSH_PRIVATE_KEY" > ssh.key
      - chmod 600 ssh.key
      - ssh-add ssh.key
      - mkdir -p ~/.ssh
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - if [ -n "${CI_COMMIT_TAG}" ]; then TAG=${CI_COMMIT_TAG}; fi
    - if [ -z "${CI_COMMIT_TAG}" ]; then TAG="latest"; fi
    - "ansible-playbook -i ansible/staging
      -e \"APP_ENV='$STAGING_APP_ENV'\"
      -e TAG=$TAG
      -e GITLAB_REPO=${CI_PROJECT_PATH}
      ansible/deploy-app.yml"
  only:
    - tags
    - master

deploy to production:
  image: williamyeh/ansible:alpine3
  stage: deploy
  environment: production
  before_script:
    - eval $(ssh-agent -s)
    - echo "$PRODUCTION_SSH_PRIVATE_KEY" > ssh.key
    - chmod 600 ssh.key
    - ssh-add ssh.key
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - "ansible-playbook -i ansible/staging
      -e \"APP_ENV='$PRODUCTION_APP_ENV'\"
      -e TAG=${CI_COMMIT_TAG}
      -e GITLAB_REPO=${CI_PROJECT_PATH}
      ansible/deploy-app.yml"
  only:
    - tags
  when: manual