language: php
sudo: required
cache:
  timeout: 2000
  directories:
  - vendor # Composer packages
  - node_modules # NPM packages

php:
  - '7.2'

addons:
  chrome: stable
  hosts:
    - dev.gzero.pl
    - api.dev.gzero.pl

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.21.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - cp .env.example .env
  - chmod 777 -R storage
  - docker version
  - docker-compose version
  - docker-compose up -d
  - docker-compose exec web phpdismod xdebug # disabling xdebug to speed up composer
  - ./develop composer install -d /var/www/ --prefer-dist --no-interaction --no-suggest --no-progress || true
  - docker-compose run --rm -w /var/www node npm -s install
  - ./develop artisan key:generate
  - ./develop artisan passport:keys
  - ./develop artisan migrate:fresh
  - ./tests/chromedriver --url-base=/wd/hub --whitelisted-ips="" & pid1="$!"

script:
  - docker-compose run --rm -w /var/www node npm -s run lint
  - docker-compose run --rm -w /var/www node npm -s test -- --verbose
  - ./develop test-travis

after_script:
 - kill $pid1 # shutdown chrome driver

after_failure:
  - ./develop logs web

matrix:
  fast_finish: true
