language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mysql -e 'create database `gzero-tests`;'

script:
  - mkdir -p build/logs
  - ./vendor/bin/codecept run --coverage --coverage-xml --coverage-html
  - cp tests/_output/coverage.xml build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
