sudo: required

language: php

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.5.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose up -d
  - docker exec -i -t platform_web_1 composer install -d /var/www/ --prefer-source --no-interaction --dev

script:
  - docker exec -i -t platform_web_1 php /var/www/vendor/bin/codecept run -c /var/www/codeception.yml --coverage --coverage-xml --coverage-html --env platform
  - docker exec -i -t platform_web_1 mkdir -p /var/www/build/logs
  - docker exec -i -t platform_web_1 cp /var/www/tests/_output/coverage.xml /var/www/build/logs/clover.xml

after_script:
  - docker exec -i -t platform_web_1 /var/www/vendor/bin/coveralls -v

#language: php
#
#php:
#  - 5.5
#  - 5.6
#  - hhvm
#
#before_script:
#  - composer self-update
#  - composer install --prefer-source --no-interaction --dev
#  - mysql -e 'create database `gzero-tests`;'
#
#script:
#  - mkdir -p build/logs
#  - ./vendor/bin/codecept run --coverage --coverage-xml --coverage-html --env platform
#  - cp tests/_output/coverage.xml build/logs/clover.xml
#
#after_script:
#  - php vendor/bin/coveralls -v
#
#matrix:
#  allow_failures:
#    - php: hhvm
#  fast_finish: true
