language: php
sudo: required
cache:
  timeout: 2000
  directories:
  - vendor # Composer packages
  - node_modules # NPM packages

php:
  - '7.1'

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.16.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker version
  - docker-compose version
  - docker-compose up -d
  - docker-compose run --rm -w /var/www node_server npm -s install
  - docker-compose exec web_server phpdismod xdebug # disabling xdebug to speed up composer
  - docker-compose exec web_server composer install -d /var/www/ --prefer-dist --no-interaction --no-suggest --no-progress || true
  - docker-compose exec web_server phpenmod xdebug # enabling xdebug for code coverage

script:
  - docker-compose run --rm -w /var/www node_server npm -s run lint
  - docker-compose run --rm -w /var/www node_server npm -s test -- --verbose
  - "docker-compose exec web_server php /var/www/vendor/bin/codecept run -c /var/www/codeception.yml -o \"settings: lint:false\" --env platform"

matrix:
  fast_finish: true
