language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source
  - composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - phpunit -d memory_limit=1024M --exclude-group ignore --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
