sudo: required

language: php

php:
  - '7.0'

services:
  - docker

env:
  DOCKER_VERSION: 1.10.3-0~trusty
  DOCKER_COMPOSE_VERSION: 1.7.1

before_install:
  - apt-cache madison docker-engine # list docker-engine versions
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION} # upgrade docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker version
  - docker-compose version
  - docker-compose up -d
  - docker exec -i -t platform_dev_web_1 phpdismod xdebug # disabling xdebug to speed up composer
  - docker exec -i -t platform_dev_web_1 composer install -d /var/www/ --prefer-source --no-interaction

script:
  - docker exec -i -t platform_dev_web_1 php /var/www/vendor/bin/codecept run -c /var/www/codeception.yml --coverage --coverage-xml --env platform
  - docker exec -i -t platform_dev_web_1 mkdir -p /var/www/build/logs
  - docker exec -i -t platform_dev_web_1 cp /var/www/tests/_output/coverage.xml /var/www/build/logs/clover.xml

after_script:
  - docker exec -it platform_dev_web_1 bash -c "export TRAVIS=$TRAVIS && export TRAVIS_JOB_ID=$TRAVIS_JOB_ID && cd /var/www && vendor/bin/coveralls -v"

matrix:
  fast_finish: true
