version: '2.1'
services:
  proxy_server:
    image: jwilder/nginx-proxy:alpine
    restart: "no"
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./.server/ssl:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
     - gznet
  web_server:
    image: gzero/platform-container:v3
    restart: "no"
    ports:
      - "8080:80"
    depends_on:
      - db_server
      - redis_server
    environment:
      OVERRIDE_UMASK: "002"
      XDEBUG: "true"
      DEFAULT_HOST: "dev.gzero.pl"
      VIRTUAL_HOST: "dev.gzero.pl,api.dev.gzero.pl,www.dev.gzero.pl"
      PHP_IDE_CONFIG: "serverName=dev.gzero.pl"
    volumes:
      - .:/var/www
    networks:
     - gznet
  db_server:
    image: postgres:9.6-alpine
    restart: "no"
    networks:
     - gznet
    volumes:
     - ./backups:/backups
     - dbdata:/var/lib/postgresql
    networks:
     - gznet
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "gzero_cms"
      POSTGRES_DB: "gzero_cms"
  db_tests_server:
    image: postgres:9.6-alpine
    restart: "no"
    networks:
     - gznet
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "gzero_cms"
      POSTGRES_DB: "gzero_cms"
  redis_server:
    image: redis:3-alpine
    restart: "no"
    volumes:
     - redisdata:/data
    networks:
     - gznet
    ports:
      - "6379:6379"
  node_server:
    image: node:6
    restart: "no"
    volumes:
      - .:/var/www
networks:
  gznet:
    driver: "bridge"
    enable_ipv6: false
volumes:
  dbdata:
    driver: "local"
  redisdata:
    driver: "local"