version: '3.6'
services:

  proxy:
    image: traefik:1.6
    command: -c /traefik.toml
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - .server/traefik.toml:/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - gzero-net

  web:
    image: gzero/platform-web-container:v5.0.0-rc3
    restart: "no"
    ports:
      - "8080:80"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=web"
      - "traefik.frontend.rule=Host:dev.gzero.pl,api.dev.gzero.pl,www.dev.gzero.pl"
    depends_on:
      - db
      - redis
    environment:
      OVERRIDE_UMASK: "002"
      XDEBUG: "true"
      DEFAULT_HOST: "dev.gzero.pl"
      PHP_IDE_CONFIG: "serverName=dev.gzero.pl"
    volumes:
      - .:/var/www
    networks:
     - gzero-net

  worker:
    image: gzero/platform-worker-container:v5.0.0-rc3
    restart: "no"
    depends_on:
      - db
      - redis
    environment:
      MODE: "horizon"
      OVERRIDE_UMASK: "002"
      XDEBUG: "true"
      PHP_IDE_CONFIG: "serverName=dev.gzero.pl"
    volumes:
      - .:/var/www
    networks:
     - gzero-net

  cron:
    image: gzero/platform-worker-container:v5.0.0-rc3
    restart: "no"
    depends_on:
      - db
      - redis
    environment:
      MODE: "cron"
      OVERRIDE_UMASK: "002"
    volumes:
      - .:/var/www
    networks:
     - gzero-net

  redis:
    image: redis:3-alpine
    restart: "no"
    volumes:
     - redisdata:/data
    ports:
      - "6379:6379"
    networks:
     - gzero-net

  db:
    image: postgres:9.6-alpine
    restart: "no"
    volumes:
     - ./backups:/backups
     - dbdata:/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "gzero_cms"
      POSTGRES_DB: "gzero_cms"
    networks:
     - gzero-net

  db_tests:
    image: postgres:9.6-alpine
    restart: "no"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "gzero_cms"
      POSTGRES_DB: "gzero_cms"
    networks:
     - gzero-net

  node:
    image: node:8
    restart: "no"
    volumes:
      - .:/var/www
    networks:
     - gzero-net

networks:
  gzero-net:

volumes:
  dbdata:
    driver: "local"
  redisdata:
    driver: "local"