web:
  build: .
  environment:
    OVERRIDE_UMASK: "002"
  volumes:
    - .:/var/www
  ports:
    - "8000:80"
  links:
    - db
    - db_tests
    - redis
db:
  image: mysql:5.7
  ports:
    - "3307:3306"
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    MYSQL_USER: "gzero-cms"
    MYSQL_PASSWORD: "test"
    MYSQL_DATABASE: "gzero-cms"
db_tests:
  image: mysql:5.7
  ports:
    - "3308:3306"
  environment:
    MYSQL_ROOT_PASSWORD: ''
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: "gzero-cms"
redis:
  image: redis:3
  ports:
    - "6379:6379"
