---
- hosts: all
  remote_user: root
  tasks:
    - name: Creates backups directory
      file: path=/root/backups state=directory owner=www-data group=www-data mode=0755
    - name: Copy docker-compose file
      template: src=../templates/staging-compose.yml dest=/root/docker-compose.yml force=yes
    - name: Copy env file
      template: src=../templates/env dest=/root/env force=yes
    - name: Stop existing containers
      shell: docker-compose -p staging stop
    - name: Destroy existing containers
      shell: docker-compose -p staging rm -f
    - name: Pull new containers
      shell: docker-compose -p staging pull
    - name: Run new containers
      shell: docker-compose -p staging up -d
    - name: Remove old volumes
      shell: docker volume ls -qf dangling=true | xargs -r docker volume rm
    - name: Remove old images
      shell: docker images -q --no-trunc | xargs -r docker rmi || true
    - name: Wait for docker containers
      wait_for:
          port: 443
          delay: 15
          state: drained
          timeout: 300
    - name: Run migrations
      shell: docker exec -i staging_web_server_1 ./commandWrapper.sh php /var/www/artisan migrate --force
    - name: Install passport password client
      shell: docker exec -i staging_web_server_1 ./commandWrapper.sh php /var/www/artisan passport:client --password
    - name: Install passport password client
      shell: docker exec -i staging_web_server_1 ./commandWrapper.sh php /var/www/artisan passport:client --personal
    - name: Publish assets
      shell: docker exec -i staging_web_server_1 ./commandWrapper.sh php /var/www/artisan vendor:publish --tag=public --force