version: "2"
services:
  web_server:
    image: registry.gitlab.com/grupazero/staging:{{ APP_VERSION | default('latest', true) }}
    restart: "always"
    environment:
      OVERRIDE_UMASK: "022"
      NGINX_HOST: "{{ DOMAIN | default('staging.gzero.pl') }}"
      SSL: "{{ SSL | default('true') }}"
    volumes:
      - ./env:/var/www/.env # We need to pass all credentials
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gznet
  db_server:
    image: postgres:9.6-alpine
    restart: "always"
    networks:
      - gznet
    volumes:
      - ./backups:/backups
      - dbdata:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: {{ POSTGRES_PASSWORD }}
      POSTGRES_USER: {{ POSTGRES_USER }}
      POSTGRES_DB: {{ POSTGRES_DATABASE }}
  redis_server:
    image: redis:3-alpine
    restart: "always"
    volumes:
      - redisdata:/data
    networks:
      - gznet
networks:
  gznet:
    driver: "bridge"
volumes:
  dbdata:
    driver: "local"
  redisdata:
    driver: "local"