---
- hosts: all
  name: Disable root user - only sudoing from regular user allowed
  tasks:
    - name: Disable root from ssh'ing
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      notify: Restart sshd

    - name: Disable root password
      shell: passwd -l root

  handlers:
    - name: Restart sshd
      service:
        name: ssh
        state: restarted
